### ISSUE TITLE
integration only works for a few hours

### ISSUE THREAD

**Issue by dnouls** [shamanenas/has_domintell#3]
I have a working version of this plugin to control my domintell installation.
It works for a few hours and then I need to reboot it to make it work again.

Is there a way to debug this issue ?

**Comment by dnouls** [comment]
I did some investigation, the integration stops working after this log statement:
```
2021-03-14 08:48:32 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [547984631792] Disconnected: Did not receive auth message within 10 seconds
```

Is anybody monitoring these issues ?

**Comment by zilvinasbin** [comment]
Hello,
this is my hobby project, so I'm not monitoring comments here. Just reading it from time to time. I using this plugin to control my domintell integration for 3 years already. And it is more or less stable. 

Looks like your problem is the configuration on Domintell side. Check the **Session timeout** parameter here. Increase it, or remove checkbox at all.  
![2021-03-17_20-22-14](https://user-images.githubusercontent.com/3399206/111518409-b6e3f380-875e-11eb-8988-2efd44c0bf18.png)

**Comment by dnouls** [comment]
Where do you have that panel in your domintell software ? I can't find it anywhere.

**Comment by zilvinasbin** [comment]
Checks this out :) ![2021-03-18_16-26-26](https://user-images.githubusercontent.com/3399206/111644042-1f3adf80-8808-11eb-8fd1-a622a439ae33.png)
![2021-03-18_16-26-55](https://user-images.githubusercontent.com/3399206/111644059-22ce6680-8808-11eb-87a5-9595ba8793e2.png)

**Comment by dnouls** [comment]
Ah great thanks for the help. I will change my setup and see if that indeed solves the problem.

**Comment by dnouls** [comment]
I changed my settings as proposed and the integration is still working after an entire night. I will close this issue. If it comes back I can always reopen... but I am feeling hopeful. Thanks for the help, I appreciate it that you make your hobby project available like this.
